### ISSUE TITLE
Checkpoint 2 Ready for Review

### ISSUE THREAD

**Issue by qtgiebel** [qtgiebel/admin#1]
@pawaitemadisoncollege Added my project to my aws deployment: [Portfolio](http://www.quinngiebel.com/portfolio), [Admin site with JS prototype ui](http://www.quinngiebel.com/admin/) and [Admin site showing some of the functionality](http://www.quinngiebel.com/admin/old_index.jsp) (Only the list pieces option functions currently).
![image](https://user-images.githubusercontent.com/18682113/155920771-ba704c08-3ddd-4665-a099-1ac074b6a303.png)
I have been working with AWS for a little while now, so that did not prove too challenging.  Hibernate was a fairly large hill to climb, but I was able to get it mostly figured out.

**Comment by pawaitemadisoncollege** [comment]
Wow! It's exciting to see this out on AWS! Lots of good progress here!

- [ ] I think you mentioned in class today that you weren't sure if this would remain as a separate repository. If it does stick around, having a readme.md here would be helpful. What do you think about also including a link to the rest of the project?
- [ ] I'm curious about using this https://github.com/qtgiebel/admin/blob/e939634a420a94f35d5ffe21199ade3696cc1945/src/main/java/com/quinngiebel/admin/persistence/PieceDao.java#L17-L33 versus updating the value on the entity and doing a SaveOrUpdate, like you would if you were to want to update the category, title or location. 
- [ ] Unit testing could be more thorough. For example, adding a piece, updating a piece. Also consider testing associations - for example, if a category is deleted, what happens to any associated pieces? If a piece is deleted, do the categories stick around? It's nice to have tests to verify what should happen, does happen, so that if the db constraints or an annotation is changed, the test will catch it. 
- [ ] Are your project plan and journal/time log up-to-date?

**Comment by qtgiebel** [comment]
> If it does stick around

It will not be sticking around, because I will need to use some of the admin persistence classes in the portfolio and that will be much easier to manage if they are in the same repository. 

> I'm curious about using this 
>
>       admin/src/main/java/com/quinngiebel/admin/persistence/PieceDao.java
>         Lines 17 to 33  in  e939634
>                /** 
>                 * Archives a piece. 
>                 * @param toArchive The piece being archived 
>                 */ 
>         ...
>  versus updating the value on the entity and doing a SaveOrUpdate, like you would if you were to want to update the category, title or location.

I had assumed that is what I was doing, but please correct me if I'm wrong. I would be getting the entity that needs to be updated, changing the archived value, and then sending it to the generic update method here where it would perform a SaveOrUpdate:
https://github.com/qtgiebel/admin/blob/e939634a420a94f35d5ffe21199ade3696cc1945/src/main/java/com/quinngiebel/admin/persistence/GenericDao.java#L79-L85 

If there is a better way to implement that, please let me know. 

> Unit testing could be more thorough.

I will go ahead and add more thorough tests. 

>  Are your project plan and journal/time log up-to-date?

They are not. I will get that updated.

**Comment by pawaitemadisoncollege** [comment]
For updating various values on the Piece, I'm imagining the current flow as something like:

1. the decision to update is made somewhere, let's say a controller, 
2. that controller code calls PieceDao.archivePiece(pieceToArchive); which calls pieceToArchive.setArchived(true); 
3. and then calls the GenericDao.update(pieceToArchive).

This could also be done like this:

1. decision is to update is made, and the value is updated on the piece object: pieceToArchive.setArchive(true); 
//could also set any other values as needed
2. call dao.update(pieceToArchive);

**Comment by qtgiebel** [comment]
You are right about the way it is set up currently, but that was intentional. The only value I currently envision updating is the archival status so for the sake of readability within the controller I would prefer to leave the update call as it is.

**Comment by pawaitemadisoncollege** [comment]
Thanks for clarifying!
